spring:
  application:
    name: SocksBackend
  datasource:
    username: socks_user
    password: socks_password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/socks_db
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  address: localhost
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    enabled: true
    path: /index.html
    display-request-duration: true
    disable-swagger-default-url: true
  api-docs:
    enabled: true
    path: /v1/api-docs